import type { Metadata } from "next";
import { Inter,Tangerine } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const tangerine = Tangerine({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-tangerine"
});

export const metadata: Metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${tangerine.variable} antialiased`}>
        <div className="w-full min-h-screen flex flex-col bg-gradient-to-b from-blue-100 to-sky-300">
          <div className="h-12 mt-10 mx-[10%]">
            <Navbar/>
          </div>
          
          <div className="flex-grow">
            <StairTransition/>
            <PageTransition>
              {children}
            </PageTransition>
          </div>
        </div>
      </body>
    </html>
  );
}
